/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */ 
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mTF = new javax.swing.JTextField();
        tdTF = new javax.swing.JTextField();
        emTF = new javax.swing.JTextField();
        licTF = new javax.swing.JTextField();
        miTF = new javax.swing.JTextField();
        csTF = new javax.swing.JTextField();
        tTF = new javax.swing.JTextField();
        eTF = new javax.swing.JTextField();
        lTF = new javax.swing.JTextField();
        msiTF = new javax.swing.JTextField();
        cTF = new javax.swing.JTextField();
        mathsTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        averageTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gpaTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setText("GPA CALCULATOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 14, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel2.setText("Maths");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 71, 78, 28));

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel3.setText("EM-II");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 159, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel4.setText("T&D");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 117, 70, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel5.setText("LIC");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 217, 70, 28));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel6.setText("M&I");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 259, 70, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel7.setText("CS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 312, 70, -1));

        mTF.setEditable(false);
        getContentPane().add(mTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 76, 71, -1));
        getContentPane().add(tdTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 119, 71, -1));
        getContentPane().add(emTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 161, 71, -1));
        getContentPane().add(licTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 222, 71, -1));
        getContentPane().add(miTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 261, 71, -1));
        getContentPane().add(csTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 312, 71, -1));

        tTF.setEditable(false);
        getContentPane().add(tTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 119, 71, -1));

        eTF.setEditable(false);
        getContentPane().add(eTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 161, 71, -1));

        lTF.setEditable(false);
        getContentPane().add(lTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 222, 71, -1));

        msiTF.setEditable(false);
        getContentPane().add(msiTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 261, 71, -1));

        cTF.setEditable(false);
        getContentPane().add(cTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 312, 71, -1));
        getContentPane().add(mathsTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 76, 71, -1));

        jButton1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 324, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel8.setText("AVG");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 104, 70, -1));
        getContentPane().add(averageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 144, 78, 43));

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel9.setText("GPA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 223, 70, -1));
        getContentPane().add(gpaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 251, 78, 43));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Calculate all grades
        
        String MathsScore,MIScore,EM_IIScore,CSScore,LICScore,T_DScore;
        double average;
        double gpa=0;
        
        MathsScore= mathsTF.getText();
        MIScore= miTF.getText();
        T_DScore= tdTF.getText();
        EM_IIScore= emTF.getText();
        CSScore= csTF.getText(); 
        LICScore= licTF.getText();
        double Maths = Double.parseDouble(MathsScore);
        double MI = Double.parseDouble(MIScore);
        double TD = Double.parseDouble(T_DScore);
        double EMII = Double.parseDouble(EM_IIScore);
        double CS = Double.parseDouble(CSScore);
        double LIC = Double.parseDouble(LICScore);
        
        average = ((Maths+MI+TD+EMII+CS+LIC)/6);
        
        //maths
        if (Maths>=90)
        {
            mTF.setText("A");
            gpa = gpa+8.0;
        }
        else if(Maths>=80 && Maths<90)
                {
                     mTF.setText("B");
                     gpa = gpa+7.0;
                }
        else if (Maths>=70 && Maths<80)
                {
                    mTF.setText("C");
                    gpa = gpa+6.0;
                }
        else if (Maths>=60 && Maths<70)
                {
                    mTF.setText("D");
                    gpa = gpa+5.0;
                }
        else 
        {
            mTF.setText("F");
            gpa = gpa+2.25;
        }
        
        //M&I
        if (MI>=90)
        {
            msiTF.setText("A");
            gpa = gpa+8.0;
        }
        else if(MI>=80 && MI<90)
                {
                     msiTF.setText("B");
                     gpa = gpa+7.0;
                }
        else if (MI>=70 && MI<80)
                {
                    msiTF.setText("C");
                    gpa = gpa+6.0;
                }
        else if (MI>=60 && MI<70)
                {
                    msiTF.setText("D");
                    gpa = gpa+5.0;
                }
        else 
        {
            msiTF.setText("F");
            gpa = gpa+2.25;
        }
        
        //T&D
        if (TD>=90)
        {
            tTF.setText("A");
            gpa = gpa+8.0;
        }
        else if(TD>=80 && TD<90)
                {
                     tTF.setText("B");
                     gpa = gpa+7.0;
                }
        else if (TD>=70 && TD<80)
                {
                    tTF.setText("C");
                    gpa = gpa+6.0;
                }
        else if (TD>=60 && TD<70)
                {
                    tTF.setText("D");
                    gpa = gpa+5.0;
                }
        else 
        {
           tTF.setText("F");
            gpa = gpa+2.25;
        }
        
        
        //EM_II
        if (EMII>=90)
        {
            eTF.setText("A");
            gpa = gpa+8.0;
        }
        else if(EMII>=80 && EMII<90)
                {
                     eTF.setText("B");
                     gpa = gpa+7.0;
                }
        else if (EMII>=70 && EMII<80)
                {
                    eTF.setText("C");
                    gpa = gpa+6.0;
                }
        else if (EMII>=60 && EMII<70)
                {
                    eTF.setText("D");
                    gpa = gpa+5.0;
                }
        else 
        {
           eTF.setText("F");
            gpa = gpa+2.25;
        }
        
        //CS
        if (CS>=90)
        {
            cTF.setText("A");
            gpa = gpa+8.0;
        }
        else if(CS>=80 && CS<90)
                {
                     cTF.setText("B");
                     gpa = gpa+7.0;
                }
        else if (CS>=70 && CS<80)
                {
                    cTF.setText("C");
                    gpa = gpa+6.0;
                }
        else if (CS>=60 && CS<70)
                {
                    cTF.setText("D");
                    gpa = gpa+5.0;
                }
        else 
        {
           cTF.setText("F");
            gpa = gpa+2.25;
        }
        
        //LIC
        if (LIC>=90)
        {
            lTF.setText("A");
            gpa = gpa+8.0;
        }
        else if(LIC>=80 && LIC<90)
                {
                     lTF.setText("B");
                     gpa = gpa+7.0;
                }
        else if (LIC>=70 && LIC<80)
                {
                    lTF.setText("C");
                    gpa = gpa+6.0;
                }
        else if (LIC>=60 && LIC<70)
                {
                    lTF.setText("D");
                    gpa = gpa+5.0;
                }
        else 
        {
           lTF.setText("F");
            gpa = gpa+2.25;
        }//finish
        
        gpa =gpa/6;
        
        gpaTF.setText(Double.toString(gpa));
        averageTF.setText(Double.toString(average));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField averageTF;
    private javax.swing.JTextField cTF;
    private javax.swing.JTextField csTF;
    private javax.swing.JTextField eTF;
    private javax.swing.JTextField emTF;
    private javax.swing.JTextField gpaTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lTF;
    private javax.swing.JTextField licTF;
    private javax.swing.JTextField mTF;
    private javax.swing.JTextField mathsTF;
    private javax.swing.JTextField miTF;
    private javax.swing.JTextField msiTF;
    private javax.swing.JTextField tTF;
    private javax.swing.JTextField tdTF;
    // End of variables declaration//GEN-END:variables
}
